[[redirects]]
  from = "/api/*"
  to = "https://34.50.47.209/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/oauth2/*"
  to = "https://34.50.47.209/oauth2/:splat"
  status = 200
  force = true