import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "../components/Header";
import QueryProvider from "./lib/providers/QueryProvider";
import MuiProvider from "./lib/providers/MuiProvider";
import Box from "@mui/material/Box";
import ClientModalRender from "../components/modal/ClientModalRender";
import Footer from "../components/Footer";
import AuthInit from "@/components/auth/AuthInit";
import GlobalSnackbar from "@/components/GlobalSnackbar";
import ClientOnlyWrapper from "@/components/ClientOnlyWrapper";
import ScrollToTop from "@/app/utils/scrollToTop";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <script src="https://developers.kakao.com/sdk/js/kakao.js"></script>
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <QueryProvider>
          <AuthInit>
            <MuiProvider>
              <ClientOnlyWrapper>
                <Header />
              </ClientOnlyWrapper>

              <Box className="bg-zinc-50 font-sans min-h-screen">
                <main className="max-w-7xl mx-auto py-8 px-4 sx:px-6 md:px-12">
                  {children}

                  <ClientModalRender />
                </main>
                <Footer />
              </Box>
              <GlobalSnackbar />
            </MuiProvider>
            <ScrollToTop />
          </AuthInit>
        </QueryProvider>
      </body>
    </html>
  );
}
