import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "../components/Header";
import QueryProvider from "./lib/providers/QueryProvider";
import MuiProvider from "./lib/providers/MuiProvider";
import Box from "@mui/material/Box";
import ClientModalRender from "../components/modal/ClientModalRender";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <script src="https://developers.kakao.com/sdk/js/kakao.js"></script>
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <QueryProvider>
          <MuiProvider>
            <Header />
            <Box className="bg-zinc-50 font-sans min-h-screen">
              <main className="max-w-3xl mx-auto py-16 sm:px-6">
                {children}
                <ClientModalRender />
              </main>
            </Box>
          </MuiProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
